### ISSUE TITLE
Can't get the rojo serve to work

### ISSUE THREAD

**Issue by MarkoCrack** [mandrillxx/eatventure-rblx#3]
Is there any .rbxl file I could use?

**Comment by MarkoCrack** [comment]
D:

**Comment by mandrillxx** [comment]
This repo is meant to be a learning utility for anyone interested in rbxts development. Although I agree a place file would make the game run without as much tinkering, this specific repository isn't meant to be 100% complete. It is something I'm open to in the future though once I am more experienced and can write more production-ready work.
